In [9]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd

print(pd.__version__)

names = ['bob', 'jack', 'tom', 'rose', 'mary']
births = ['1992-01-11', '1995-01-08', '1992-11-11', '1992-10-22', '1992-08-21']

people = list(zip(names, birth))
print(people)

0.20.3
[('bob', '1992-01-11'), ('jack', '1995-01-08'), ('tom', '1992-11-11'), ('rose', '1992-10-22'), ('mary', '1992-08-21')]

In [10]:
df = pd.DataFrame(data = people, columns = ['Names', 'Births'])
df

  Names      Births
0   bob  1992-01-11
1  jack  1995-01-08
2   tom  1992-11-11
3  rose  1992-10-22
4  mary  1992-08-21

In [21]:
df.to_csv('births1880.csv', index = False, header = False)

In [22]:
file_path =r'/Users/xwy_brh/Downloads/AI/notebook-play/births1880.csv'
rf = pd.read_csv(file_path, header = None, names = ["Names", "Births"])
rf

  Names      Births
0   bob  1992-01-11
1  jack  1995-01-08
2   tom  1992-11-11
3  rose  1992-10-22
4  mary  1992-08-21

In [19]:
import os
os.remove(file_path)

In [24]:
stock_file_path = r'/Users/xwy_brh/Downloads/AI/dataSets/stock_train_data_20170901.csv'
sf = pd.read_csv(stock_file_path, nrows=300)
sf

,id,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature82,feature83,feature84,feature85,feature86,feature87,weight,label,group,era
0,0,-1.173882,1.538027,1.275714,-0.013584,-2.546444,1.087728,-1.749776,2.435902,2.009132,...,0.958151,-0.563945,-0.392385,-0.391147,-0.682026,1.849691,3.0,1.0,15,1
1,1,-1.178808,1.397968,0.901504,1.469173,-2.179160,0.410564,-1.630442,1.798660,1.335881,...,-0.120476,0.579327,0.680619,0.435993,-0.393109,1.751096,2.0,0.0,15,1
2,2,-1.114238,1.026806,-1.393255,1.175937,-0.868198,0.660903,-0.635268,1.552341,1.802073,...,2.143082,1.608187,0.863711,1.194580,-0.131755,1.123568,13.0,0.0,19,1
3,3,-0.664808,1.108403,-0.894371,0.883911,-0.592890,0.235681,0.351029,0.357797,0.459479,...,-0.328402,0.926607,1.002191,0.611524,0.564266,0.016037,4.0,1.0,17,1
4,4,-0.392408,1.389080,0.040249,4.006332,-1.629613,0.553216,-0.985631,1.568299,1.645098,...,0.098118,1.286548,1.278155,0.902573,0.124226,0.784359,5.0,0.0,28,1
5,5,-0.400484,-0.587553,1.404753,-0.355609,-0.824592,1.088633,-1.307138,0.776545,0.433261,...,-0.672232,-0.039561,-0.279658,-0.030686,-0.362324,0.105802,1.0,1.0,3,1
6,6,-1.260995,-1.297146,-1.397739,0.237993,-1.535000,0.964815,-1.245962,1.631029,1.504546,...,2.480278,-0.423729,-0.255198,-0.289934,0.359408,2.459450,11.0,0.0,13,1
7,7,-0.655226,0.719243,-0.448219,2.592721,-1.968366,1.092013,-1.195913,1.088869,0.884293,...,-0.175367,0.409660,0.637523,1.284556,2.183676,0.480744,1.0,1.0,19,1
8,8,0.340032,0.303219,0.440998,1.144836,0.103850,-1.117281,0.011960,0.172056,0.415492,...,-0.959226,0.019762,0.261726,0.005494,-0.063215,-0.668846,7.0,0.0,7,1
9,9,-0.170870,-0.992091,1.501305,1.037615,-0.366572,-1.154542,-0.670935,0.667217,0.792387,...,-0.348262,1.073890,2.031839,0.731423,-0.119910,0.092660,5.0,1.0,22,1
10,10,-0.497007,1.336646,-0.964323,4.337978,-0.702962,0.263371,0.124267,0.208996,0.481599,...,-0.432108,1.555776,1.627909,1.158105,0.066115,-0.345220,14.0,0.0,18,1
11,11,-0.753392,-0.947149,-0.208691,0.967405,-1.669028,1.014876,-0.841828,0.331864,0.436541,...,-0.680772,-0.372687,-0.421066,-0.257606,-0.534438,0.293640,1.0,1.0,19,1
12,12,0.542437,0.991069,-0.979245,-0.728891,0.206301,-1.090838,-2.440458,1.838107,0.715917,...,1.516242,0.316923,0.134892,0.247871,-0.768419,1.191463,4.0,1.0,3,1
13,13,-0.354266,-0.185309,1.368363,0.066877,-0.212386,-1.574453,-1.353621,0.719642,0.517980,...,-0.434973,1.278951,0.654362,0.931162,0.307229,0.346118,4.0,1.0,21,1
14,14,-0.151892,0.074908,0.583284,0.245281,-0.943131,-0.085935,-0.063719,0.687880,0.492084,...,-0.218562,1.300605,2.762333,0.899912,1.332691,-0.033612,10.0,1.0,8,1
15,15,-0.596425,-0.595943,-1.379865,1.691160,-1.020941,0.657100,0.194488,-0.060253,0.281539,...,-0.427923,0.674326,0.813853,0.358020,0.295206,-0.146246,0.0,0.0,15,1
16,16,-1.293801,1.383009,0.331795,0.139031,-2.772321,1.051299,-1.705306,1.614313,0.971480,...,-0.504688,-0.109857,-0.011665,-0.077105,-0.447891,1.613693,7.0,0.0,7,1
17,17,-1.222196,1.077064,-1.074205,0.283047,-1.205671,1.065930,-1.051236,1.995225,2.303525,...,1.345012,0.775568,1.031468,0.403535,-0.083594,1.616892,3.0,0.0,15,1
18,18,-0.890645,-0.509111,1.584234,-0.874007,-1.235928,-1.626932,-1.926401,0.826861,0.390449,...,-0.898177,-0.970631,-1.162102,-0.690906,-0.750459,0.723142,7.0,1.0,23,1
19,19,0.012193,0.142321,0.562882,-0.600309,1.120168,1.064467,0.153558,-0.362040,0.021619,...,-0.713369,-0.673151,-0.831440,-0.482692,-0.809779,-0.996686,5.0,1.0,26,1
20,20,-0.041729,1.260504,-0.414103,1.197281,-0.045002,0.636293,-0.342337,0.652506,1.051559,...,-0.381497,1.652023,0.838372,1.212798,-0.355065,-0.544101,3.0,0.0,2,1
21,21,-0.222952,-1.519792,-1.019957,1.218035,-0.224286,1.088510,0.234431,0.293603,0.499209,...,0.445729,0.476696,0.934975,0.337930,0.873763,-0.382140,9.0,0.0,3,1
22,22,-1.263324,0.918889,1.015283,-0.048965,-2.925769,0.868674,-0.997080,1.846622,2.169527,...,2.187150,-0.446907,-0.311758,-0.308358,-0.094121,1.803906,0.0,1.0,9,1
23,23,-0.493843,0.354980,-0.571255,1.016144,-0.049279,0.345904,0.822415,-0.171169,-0.246959,...,-0.394943,1.276816,1.802884,0.890740,1.054998,-0.472594,4.0,0.0,17,1
24,24,-0.510241,1.258370,0.097473,-0.486121,-1.105334,1.048314,-2.719019,3.168736,2.726809,...,2.943051,0.257965,0.938720,1.098133,0.731338,1.452450,3.0,1.0,21,1
25,25,0.001017,0.778404,1.121586,-0.636263,0.855891,0.966217,0.098641,-0.377918,0.005342,...,-0.310595,-0.910971,-0.952426,-0.675581,-0.848368,-0.778512,2.0,1.0,6,1
26,26,-0.746198,1.458422,0.974397,0.603318,-0.942455,0.884421,0.077416,0.829061,0.572823,...,-0.298821,0.630063,0.957221,0.877451,0.547380,0.327866,0.0,0.0,17,1
27,27,-0.116977,-1.540904,0.500893,0.355619,-0.341486,-1.716422,-0.055873,0.210396,0.516454,...,0.255176,-0.018683,0.109142,0.003347,-0.150590,-0.636359,6.0,0.0,19,1
28,28,0.016639,1.335028,-1.006822,0.403626,-0.731075,0.918483,-1.143981,1.597269,1.268359,...,-0.186234,3.052939,4.965323,2.223285,0.696689,0.326750,17.0,0.0,14,1
29,29,-0.821018,1.041535,1.547873,-0.295363,-1.293910,-0.543133,-2.923465,2.088871,0.615098,...,-0.757612,0.445397,-0.330509,0.341777,-0.495001,1.210959,1.0,1.0,18,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,270,-0.846591,1.292438,0.348410,1.269817,-1.686492,1.094056,-1.109858,2.060673,2.245997,...,1.428229,0.015100,0.250358,-0.008555,0.040216,1.232983,5.0,0.0,8,1
271,271,-0.722141,1.267010,0.625995,1.236806,-1.921102,0.347940,-0.302454,0.372596,0.685599,...,-0.758123,0.124713,0.198668,0.112169,0.030682,0.386411,3.0,0.0,13,1
272,272,-0.514202,0.758035,-0.933278,-0.183602,-0.862650,0.164923,-0.795365,1.495134,1.795309,...,3.074393,-1.157598,-1.250127,-0.419102,-0.694919,0.213451,9.0,0.0,7,1
273,273,-0.029290,0.926212,-1.395350,-0.281102,0.906295,1.019373,-0.071398,-0.110757,0.289234,...,-0.693151,-0.411549,-0.465662,0.258836,0.446757,-0.892279,1.0,1.0,26,1
274,274,-0.580302,-1.498304,1.001577,-0.235169,-1.058257,-1.868439,0.298241,0.045638,0.518592,...,0.542798,-0.527995,-0.336727,-0.376607,0.020702,-0.062934,0.0,1.0,1,1
275,275,-1.821697,0.807808,1.178978,-0.571932,-2.283915,-1.877732,-1.987801,1.506323,0.560142,...,-0.774721,-0.026093,0.022710,-0.021353,-0.464234,2.592811,7.0,0.0,17,1
276,276,-1.513553,-0.273299,-0.159185,1.066071,-2.111326,1.087784,-1.483735,0.422500,0.149658,...,-0.690941,0.134650,-0.005187,0.092022,-0.259287,1.423289,4.0,1.0,4,1
277,277,-0.730036,-0.130042,0.733682,-0.158148,-0.920465,0.347169,-1.321433,1.149891,0.554101,...,0.293814,0.128654,0.361327,0.102320,0.104034,0.524744,5.0,1.0,3,1
278,278,-0.860542,1.352011,1.295149,0.717586,-2.003509,0.979946,-0.415767,1.799571,1.840931,...,2.136090,-0.238702,0.147405,-0.181809,-0.552253,1.359359,0.0,0.0,3,1
279,279,-0.980738,-1.052622,0.950458,-0.199693,-1.532977,1.092649,-0.686660,-0.046332,0.124811,...,-0.860184,-0.660645,-0.599702,-0.465736,-0.515244,0.533057,0.0,0.0,15,1
280,280,-1.167894,0.868056,1.314360,0.537702,-1.770647,1.063730,-0.459461,0.500694,0.678176,...,-0.303156,1.271942,1.729517,0.948488,0.298382,0.462713,8.0,0.0,17,1
281,281,-1.175956,1.009824,0.083869,0.344511,-1.899596,1.043064,-1.679101,1.759283,0.673181,...,-0.564285,0.105683,0.597425,0.100432,1.024429,1.440175,10.0,0.0,9,1
282,282,-1.258724,1.480849,1.244198,2.065835,-1.710196,1.047345,-1.767784,2.520254,2.101686,...,1.493942,0.822467,1.092668,0.608027,0.373332,1.971167,9.0,0.0,7,1
283,283,-0.948351,0.237143,1.737921,-0.252338,-1.533150,-0.802861,-1.796108,1.226790,0.478369,...,-0.571845,-0.024832,0.697500,0.000963,0.110675,1.047790,8.0,0.0,21,1
284,284,-0.230018,1.102796,-1.275996,6.488664,-0.081590,-0.971441,-0.218073,0.453654,0.551731,...,-0.873659,2.992558,1.638520,2.146680,0.407717,-0.452039,2.0,0.0,16,1
285,285,-1.533728,1.147539,-0.159800,0.104835,-1.446244,0.363222,-0.337555,1.843194,1.880610,...,2.699587,0.303386,0.775523,0.243888,1.013550,2.002040,0.0,1.0,14,1
286,286,-0.982356,1.177255,-0.514757,0.804943,-1.016659,1.001604,-0.548381,1.890105,1.927945,...,2.637951,0.118289,-0.156826,0.097633,-0.430658,0.996467,4.0,0.0,28,1
287,287,-0.986823,1.301996,0.373366,-0.163123,-2.286649,0.601932,-3.020891,2.892887,1.255716,...,0.018833,-0.091264,-0.087281,-0.068152,-0.219197,1.597847,14.0,0.0,9,1
288,288,-0.604380,1.092494,0.937537,1.742346,-1.574940,0.099322,0.027945,0.187946,0.521677,...,-0.920950,0.935623,1.529830,0.691268,2.207601,0.025625,8.0,0.0,1,1
289,289,-0.784162,1.191611,-0.631532,-0.276493,-1.704437,-0.099886,-2.106928,2.068729,1.535302,...,0.503218,-0.935756,-1.025094,-0.685635,-1.016704,1.220290,6.0,1.0,7,1
290,290,-0.329870,-0.171046,0.907804,-0.300500,-0.284528,1.095108,0.429650,0.411886,0.749074,...,0.590182,0.210518,0.650213,0.125798,0.472670,-0.392093,8.0,0.0,4,1
291,291,-1.266816,1.279943,1.486028,-0.514861,-2.224506,0.422180,-3.053892,2.532098,1.246664,...,2.054084,-1.116157,-1.125364,-0.798459,-1.121606,2.735423,9.0,1.0,11,1
292,292,-0.520674,1.152593,-0.040647,0.171640,-0.710288,0.347925,-0.307136,0.717959,0.950462,...,0.293638,0.605951,1.245480,0.454952,-0.076577,-0.115294,2.0,0.0,3,1
293,293,-1.230260,0.504558,0.999460,0.749639,-1.469314,-0.084089,-2.790910,1.788089,0.445033,...,-0.027384,0.302200,0.245619,0.232458,-0.656109,2.159176,3.0,1.0,7,1
294,294,-0.344650,1.220664,-1.191952,4.693722,-0.375405,0.971285,0.200978,0.211795,0.516978,...,-0.333569,0.805680,0.847438,0.605226,0.071109,-0.607546,4.0,0.0,7,1
295,295,-1.514200,0.862657,-0.878024,0.416072,-2.510316,0.453689,-0.833369,2.153577,2.459482,...,3.686581,0.305695,0.438301,0.243641,-0.214814,2.572562,7.0,0.0,5,1
296,296,-0.314681,0.682008,0.053428,0.697957,-0.482094,-1.349379,-1.656522,1.111623,0.520724,...,-0.432568,1.885436,1.603260,1.298655,0.063650,0.493071,10.0,1.0,3,1
297,297,-1.725083,1.554386,0.313562,-0.373196,-2.540636,1.088629,-2.463434,3.402060,2.860929,...,1.666861,-0.129155,0.289218,-0.072094,-0.514087,3.084697,10.0,0.0,14,1
298,298,-1.397526,0.306165,1.518279,0.145755,-2.306399,-1.886964,-2.747807,1.591412,0.523512,...,0.539009,-0.291936,-0.035583,-0.255542,-0.904177,1.781645,5.0,1.0,16,1
299,299,-0.377217,0.881792,1.745435,-0.092195,-1.233333,0.710826,-0.377313,0.364107,0.651263,...,-0.651688,-0.220224,-0.118450,0.510969,0.435924,-0.104311,2.0,1.0,1,1

## [10 Minutes to pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html#min)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pylot as plt

### 在pandas库中, 主要使用了两个数据类型结构
1. <em>Series</em>
    <br>
    ps.[参考链接](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html#pandas.Series)
```
    class pandas.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)[source]
```
2. DataFrame
    有点像数据库的结构

In [2]:
s = pd.Series([1, 3, 5, np.nan, 43, 9.8])
s

0     1.0
1     3.0
2     5.0
3     NaN
4    43.0
5     9.8
dtype: float64

In [4]:
dates = pd.date_range('20170920', periods = 6)
dates

DatetimeIndex(['2017-09-20', '2017-09-21', '2017-09-22', '2017-09-23',
               '2017-09-24', '2017-09-25'],
              dtype='datetime64[ns]', freq='D')

In [8]:
df = pd.DataFrame(np.random.rand(6, 5), index = dates, columns = list('ABCDE'))
df

                   A         B         C         D         E
2017-09-20  0.761733  0.120397  0.521084  0.850656  0.977919
2017-09-21  0.873333  0.112119  0.506629  0.629526  0.218005
2017-09-22  0.233203  0.140803  0.200781  0.913022  0.382804
2017-09-23  0.796658  0.088113  0.482258  0.835864  0.981236
2017-09-24  0.333129  0.479810  0.179533  0.414468  0.679449
2017-09-25  0.736676  0.471260  0.109521  0.320464  0.065104

In [15]:
df2 = pd.DataFrame({ 'A':1.,
    'B': pd.Timestamp('20170920'),
    'C': pd.Series(1, index = list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype = 'int32'),
    'E': pd.Categorical(['test', 'train', 'test', 'train']),
    'F': 'foo'})
df2

     A          B    C  D      E    F
0  1.0 2017-09-20  1.0  3   test  foo
1  1.0 2017-09-20  1.0  3  train  foo
2  1.0 2017-09-20  1.0  3   test  foo
3  1.0 2017-09-20  1.0  3  train  foo

In [16]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [18]:
df.head()

                   A         B         C         D         E
2017-09-20  0.761733  0.120397  0.521084  0.850656  0.977919
2017-09-21  0.873333  0.112119  0.506629  0.629526  0.218005
2017-09-22  0.233203  0.140803  0.200781  0.913022  0.382804
2017-09-23  0.796658  0.088113  0.482258  0.835864  0.981236
2017-09-24  0.333129  0.479810  0.179533  0.414468  0.679449

In [19]:
df.tail(3)

                   A         B         C         D         E
2017-09-23  0.796658  0.088113  0.482258  0.835864  0.981236
2017-09-24  0.333129  0.479810  0.179533  0.414468  0.679449
2017-09-25  0.736676  0.471260  0.109521  0.320464  0.065104

In [20]:
df.index

DatetimeIndex(['2017-09-20', '2017-09-21', '2017-09-22', '2017-09-23',
               '2017-09-24', '2017-09-25'],
              dtype='datetime64[ns]', freq='D')

In [22]:
df.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [23]:
df.values

array([[ 0.76173344,  0.12039738,  0.52108357,  0.85065564,  0.97791895],
       [ 0.87333338,  0.11211853,  0.50662936,  0.62952631,  0.21800535],
       [ 0.2332027 ,  0.14080277,  0.20078122,  0.91302152,  0.38280386],
       [ 0.7966579 ,  0.0881126 ,  0.48225775,  0.83586398,  0.98123572],
       [ 0.33312944,  0.47981   ,  0.17953347,  0.41446766,  0.67944873],
       [ 0.73667588,  0.47126037,  0.10952124,  0.32046444,  0.06510421]])

In [25]:
df.describe()

              A         B         C         D         E
count  6.000000  6.000000  6.000000  6.000000  6.000000
mean   0.622455  0.235417  0.333301  0.660667  0.550753
std    0.268685  0.186779  0.189091  0.248111  0.389649
min    0.233203  0.088113  0.109521  0.320464  0.065104
25%    0.434016  0.114188  0.184845  0.468232  0.259205
50%    0.749205  0.130600  0.341519  0.732695  0.531126
75%    0.787927  0.388646  0.500536  0.846958  0.903301
max    0.873333  0.479810  0.521084  0.913022  0.981236

In [26]:
df.T

   2017-09-20  2017-09-21  2017-09-22  2017-09-23  2017-09-24  2017-09-25
A    0.761733    0.873333    0.233203    0.796658    0.333129    0.736676
B    0.120397    0.112119    0.140803    0.088113    0.479810    0.471260
C    0.521084    0.506629    0.200781    0.482258    0.179533    0.109521
D    0.850656    0.629526    0.913022    0.835864    0.414468    0.320464
E    0.977919    0.218005    0.382804    0.981236    0.679449    0.065104

## axis 说明
* axis = 0 => 纵轴
* axis = 0 => 横轴

In [34]:
df.sort_index(axis = 1, ascending = False)

                   E         D         C         B         A
2017-09-20  0.977919  0.850656  0.521084  0.120397  0.761733
2017-09-21  0.218005  0.629526  0.506629  0.112119  0.873333
2017-09-22  0.382804  0.913022  0.200781  0.140803  0.233203
2017-09-23  0.981236  0.835864  0.482258  0.088113  0.796658
2017-09-24  0.679449  0.414468  0.179533  0.479810  0.333129
2017-09-25  0.065104  0.320464  0.109521  0.471260  0.736676

In [35]:
df.sort_values(by="B")

                   A         B         C         D         E
2017-09-23  0.796658  0.088113  0.482258  0.835864  0.981236
2017-09-21  0.873333  0.112119  0.506629  0.629526  0.218005
2017-09-20  0.761733  0.120397  0.521084  0.850656  0.977919
2017-09-22  0.233203  0.140803  0.200781  0.913022  0.382804
2017-09-25  0.736676  0.471260  0.109521  0.320464  0.065104
2017-09-24  0.333129  0.479810  0.179533  0.414468  0.679449